# Model Development

The objective is to build a model so as to get accurate predictions of price using one or the other features of the car price and the data from the car price dataset.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

#### Creating a linear regression object.

In [6]:
df = pd.read_csv("clean_df.csv")
lm = LinearRegression()
lm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
x = df[['highway-mpg']]
y = df[['price']]

Fitting linear model using highway-mpg :

In [8]:
lm.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Predicting the price values using the highway-mpg values of the dataset itself 

In [13]:
Yhat = lm.predict(x)
Yhat[0:5]

array([[16254.26934067],
       [17077.0977727 ],
       [13785.78404458],
       [20368.41150083],
       [17899.92620473]])

In [14]:
lm.intercept_

array([38470.6370055])

In [15]:
lm.coef_

array([[-822.82843203]])

In [12]:
df

Unnamed: 0  symboling  normalized-losses         make fuel-type  \
0             0          3              122.0  alfa-romero       gas   
1             1          1              122.0  alfa-romero       gas   
2             2          2              164.0         audi       gas   
3             3          2              164.0         audi       gas   
4             4          2              122.0         audi       gas   
..          ...        ...                ...          ...       ...   
195         195         -1               95.0        volvo       gas   
196         196         -1               95.0        volvo       gas   
197         197         -1               95.0        volvo       gas   
198         198         -1               95.0        volvo    diesel   
199         199         -1               95.0        volvo       gas   

    aspiration num-of-doors   body-style drive-wheels engine-location  ...  \
0          std          two  convertible          rwd           front  ...   
1          std          two    hatchback          rwd           front  ...   
2          std         four        sedan          fwd           front  ...   
3          std         four        sedan          4wd           front  ...   
4          std          two        sedan          fwd           front  ...   
..         ...          ...          ...          ...             ...  ...   
195        std         four        sedan          rwd           front  ...   
196      turbo         four        sedan          rwd           front  ...   
197        std         four        sedan          rwd           front  ...   
198      turbo         four        sedan          rwd           front  ...   
199      turbo         four        sedan          rwd           front  ...   

     city-mpg  highway-mpg    price  highway-L/100km  city-L/100km  \
0          21           27  16500.0         8.703704     11.190476   
1          19           26  16500.0         9.038462     12.368421   
2          24           30  13950.0         7.833333      9.791667   
3          18           22  17450.0        10.681818     13.055556   
4          19           25  15250.0         9.400000     12.368421   
..        ...          ...      ...              ...           ...   
195        23           28  16845.0         8.392857     10.217391   
196        19           25  19045.0         9.400000     12.368421   
197        18           23  21485.0        10.217391     13.055556   
198        26           27  22470.0         8.703704      9.038462   
199        19           25  22625.0         9.400000     12.368421   

    normalized-height normalized-width  normalized-length horsepower-binned  \
0            0.816054         0.890278           0.811148               Low   
1            0.876254         0.909722           0.822681            Medium   
2            0.908027         0.919444           0.848630               Low   
3            0.908027         0.922222           0.848630               Low   
4            0.887960         0.920833           0.851994               Low   
..                ...              ...                ...               ...   
195          0.928094         0.956944           0.907256               Low   
196          0.928094         0.955556           0.907256            Medium   
197          0.928094         0.956944           0.907256            Medium   
198          0.928094         0.956944           0.907256               Low   
199          0.928094         0.956944           0.907256               Low   

     price-binned  
0             Low  
1             Low  
2             Low  
3             Low  
4             Low  
..            ...  
195           Low  
196        Medium  
197        Medium  
198        Medium  
199        Medium  

[200 rows x 34 columns]